name: dactykids
description: Jeu d'apprentissage de la dactylographie pour enfants.
publish_to: "none"
version: 1.0.0+100

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  audioplayers: ^6.6.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/content/layouts/
    - assets/content/lessons/
    - assets/content/wordlists/
    - assets/images/game/
    - assets/images/game/cars/
    - assets/images/game/hands/
    - assets/images/game/hands/high_contrast/
    - assets/images/game/hands/red/
    - assets/sounds/
